name: Get latest release version
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch branch name of latest version
        run: |
          curl -sL https://api.github.com/repos/meilisearch/MeiliSearch/releases/latest | \
          jq -r ".tag_name" > /tmp/meilisearch-latest-branch-name
          echo "REMOTE_BRANCH_NAME=$(cat /tmp/meilisearch-latest-branch-name)" >> $GITHUB_ENV
          curl -sL https://github.com/patrickdung/MeiliSearch-crossbuild/raw/main/release-versions/meilisearch-latest.txt -o /tmp/meilisearch-local-branch-name
          echo "LOCAL_BRANCH_NAME=$(cat /tmp/meilisearch-local-branch-name)" >> $GITHUB_ENV          
      - name: Check for modified files
        id: git-check
        run: |
          $([ "${{ env.REMOTE_BRANCH_NAME }}" != "${{ env.LOCAL_BRANCH_NAME }}" ] && echo "true" || echo "false")
      - uses: actions/checkout@v2
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'false'
        run: |
          git config --global user.name 'Patrick Dung'
          git config --global user.email '38665827+patrickdung@users.noreply.github.com'
          echo ${{ env.REMOTE_BRANCH_NAME }} > release-versions/meilisearch-latest.txt
          git commit -am "New release version"
          git push
