name: Get latest release version
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: meilisearch/MeiliSearch
          # token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          sudo apt-get install -y curl jq
          mkdir -p release-versions
          curl -sL https://api.github.com/repos/meilisearch/MeiliSearch/releases/latest | \
          jq -r ".tag_name" > release-versions/meilisearch-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Patrick Dung'
          git config --global user.email '38665827+patrickdung@users.noreply.github.com'
          git commit -am "New release version"
          git push
